name: Tests
on:
  workflow_dispatch:
    inputs:
      project:
        description: "Test project defined in Playwright config"
        required: true
        default: "api"
        type: choice
        options:
          - api
          - bdd
      logLevel:
        description: "Log level - INFO, DEBUG, ERROR"
        required: true
        default: ERROR
        type: choice
        options:
          - INFO
          - DEBUG
          - ERROR
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install deps
        run: npx playwright install-deps
      - name: Run tests
        run: |
          echo "✅ the selected project is ${{ inputs.project }}"
          echo "✅ the selected log level is ${{ inputs.logLevel }}"
          npx playwright test  --project=api
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Print summary on success
        if: ${{ success() }}
        run: |
          echo "Playwright tests executed 🚀"
          echo "Total tests: "
